apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: microservices
type: Opaque
stringData:
  postgres_password: your-secure-password
  jwt_secret: your-secure-jwt-secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: microservices
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: default
  namespace: microservices
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-reader
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-reader-binding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
roleRef:
  kind: Role
  name: monitoring-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: logging

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana
  namespace: logging

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash
  namespace: logging
