name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd user-service
        mvn clean install
        cd ../order-service
        mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: {{ secrets.DOCKERHUB_USERNAME }}
        password: {{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        cd user-service
        docker build -t {{ secrets.DOCKERHUB_USERNAME }}/user-service:{{ github.sha }} .
        docker push {{ secrets.DOCKERHUB_USERNAME }}/user-service:{{ github.sha }}
        cd ../order-service
        docker build -t {{ secrets.DOCKERHUB_USERNAME }}/order-service:{{ github.sha }} .
        docker push {{ secrets.DOCKERHUB_USERNAME }}/order-service:{{ github.sha }}

    - name: Deploy to Kubernetes
      uses: kubernetes-sigs/kustomize-action@v1
      with:
        kustomizePath: kubernetes
        kubeconfig: {{ secrets.KUBECONFIG }}
        command: apply
